### ISSUE TITLE
uninitialized constant SassC::Script::String

### ISSUE THREAD

**Issue by WillianGoncalves** [sass/sassc-rails#128]
I'm getting this error: `SassC::SyntaxError - Error: error in C function asset-data-url: uninitialized constant SassC::Script::String`. Maybe its origin is here: https://github.com/sass/sassc-rails/blob/master/lib/sassc/rails/functions.rb#L8

It looks like the `SassC::Script::String` was removed from `sass-ruby` in the commit: https://github.com/sass/sassc-ruby/commit/4731802dcde9a4c17aa6ed9d4e1784c0eeec3159#diff-36146a65a77915929f0dd69a9bb0c214L42

**Comment by lpagliari** [comment]
Should it be `::SassC::Script::Value::String` instead?

**Comment by bolandrm** [comment]
Resolved in version `2.1.2`, please give it a try and let me know how it goes!

**Comment by lpagliari** [comment]
Problem solved, thanks @bolandrm !
