### ISSUE TITLE
@import rule is not working

### ISSUE THREAD

**Issue by ghost** [sass/sassc-rails#145]
in my **application.scss**
`$global: 1px;
@import "test"`
and in **_test.scss**
`h1 {
    font-size: $global;
}`

$ rake assets:precompile
rake aborted!
SassC::SyntaxError: Error: Undefined variable: "$global".
        on line 2:16 of app/assets/stylesheets/_test.scss
>>     font-size: $global;

   ---------------^

anyone knows why...?

**Comment by marcoschicote** [comment]
@kuyenda I'm getting a similar error. How did you manage to solve it? Thanks in advance!
