### ISSUE TITLE
rb_safe_level will be removed in Ruby 3.0

### ISSUE THREAD

**Issue by dorner** [sass/sassc-rails#159]
Running Sprockets with sassc on latest Ruby 2.7, the following warnings come up over and over again:

```
/home/circleci/workspace/vendor/bundle/ruby/2.7.0/gems/sassc-1.12.1/lib/sassc/engine.rb:27: warning: rb_safe_level will be removed in Ruby 3.0
/home/circleci/workspace/vendor/bundle/ruby/2.7.0/gems/sassc-1.12.1/lib/sassc/engine.rb:29: warning: rb_safe_level will be removed in Ruby 3.0
/home/circleci/workspace/vendor/bundle/ruby/2.7.0/gems/sassc-1.12.1/lib/sassc/functions_handler.rb:31: warning: rb_safe_level will be removed in Ruby 3.0
```

I don't actually see any reference to this in the sassc code itself, nor do I have much experience with C code used by Ruby, but it sounds like this will break sassc with Ruby 3.0?

**Comment by ahorek** [comment]
sassc-1.12.1 is outdated and the warning is probably triggered by ffi https://github.com/ffi/ffi/commit/7a1016a15964762ce240216068069ef5cc246458

```
ruby -v
ruby 3.0.0dev (2020-12-16T18:46:44Z master 93ba3ac036) [x86_64-linux]

rake test
.............................S.......................................
Fabulous run in 0.799886s, 86.2623 runs/s, 1130.1610 assertions/s.

69 runs, 904 assertions, 0 failures, 0 errors, 1 skips
```

no failures, no warnings

**Comment by dorner** [comment]
Confirmed latest versions of ffi and sassc fix this. Sorry about that! Closing this.
