### ISSUE TITLE
import once

### ISSUE THREAD

**Issue by pkmiec** [sass/sassc-rails#21]
I'm trying to use sassc-rails to speed up asset compilation. With sass-rails, I've been using https://github.com/Compass/compass/tree/master/import-once. However, that doesn't seem to work with sassc-rails. Does anything like that exist yet for sassc-rails?

ps. I know sass v4 is rumored to include import once functionality. It's unclear when v4 will be out, so I'm looking for something I can use with v3.

**Comment by bolandrm** [comment]
Hey.  You're correct - this won't work with sassc-rails.  This could probably exist as a separate gem.  It might even be simpler, since we're not doing any caching with sassc-rails.

I don't immediately need this, so i'm going to mark it as `needs-contributor`.  Someone is welcome to work on this.

**Comment by pkmiec** [comment]
Thanks. I will look into it. Perhaps I can come up with a separate gem solution for sassc-rails.

**Comment by pkmiec** [comment]
I have written the initial version: http://github.com/appfolio/sassc-import_once. However, there seems to be an issue with libsass which prevents "import once" type of functionality, https://github.com/sass/libsass/issues/1262.

**Comment by rubenswieringa** [comment]
@pkmiec can you confirm that the breadth-first/depth-first issue has been solved as stated in  sass/libsass#1262? And I noticed your gem isn't available through rubyforge yet, is there any more work that needs to be done on it?

**Comment by pkmiec** [comment]
I'm on vacation for the next week. I can look into it when I get back.

**Comment by rubenswieringa** [comment]
Cool, let me know :)

**Comment by pkmiec** [comment]
@rubenswieringa 

Indeed, the issue is fixed. Hooray! I've updated the gem to depend on sassc ~> 1.8 and enabled additional tests. The first version of the gem is now available on rubygems.

I've yet to use this on my own project, so let me know if it work / doesn't work for you.
