### ISSUE TITLE
Integrate sassc-rails work on sass-rails

### ISSUE THREAD

**Issue by rafaelfranca** [sass/sassc-rails#40]
After https://github.com/rails/sprockets/pull/80 is merged we will have first class sassc support on sprockets. The plan is to make sass-rails work with both sass and sassc so I believe it may be better to integrate sassc-rails work back to sass-rails and have only one gem to integrate sass in Rails applications.

Do you think it is possible?

I can grant commit access to this gem maintainers there.

**Comment by bolandrm** [comment]
@rafaelfranca   I agree, and I should be to do this.  My main concern is that the file importers are very different, so it won't really be seamless (there might be small inconsistencies).  We might be able to extract the common portions of the importers though.

I won't have time to work on this until the end of the month though.

**Comment by bolandrm** [comment]
@rafaelfranca do you want to *remove* support for the standard, ruby-sass in sass-rails, and only allow the use of libsass?  Or do you want to preserve both?

**Comment by rafaelfranca** [comment]
My initial idea is to preserve both since sprockets will support both.

**Comment by bolandrm** [comment]
@rafaelfranca I can work on this soon.  I would like to address some of the open issues in `sass-rails` first though.

**Comment by bolandrm** [comment]
WIP here.  https://github.com/rails/sass-rails/pull/349
