### ISSUE TITLE
Malformed URL error if schema omitted.

### ISSUE THREAD

**Issue by roman-yarovoy** [sass/sassc-rails#42]
I catch such error on compiling https://github.com/rstgroup/active_skin/blob/master/app/assets/stylesheets/active_skin.css.sass

```
Error: malformed URL
        on line 1 of active_skin
>> @import url(//fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700&subs
```

Looks like bug.

**Comment by bolandrm** [comment]
@roman-yarovoy Link is broken, can you please post the CSS?

**Comment by roman-yarovoy** [comment]
@bolandrm here it is - https://github.com/rstgroup/active_skin/blob/master/app/assets/stylesheets/active_skin.sass, first line: 
```sass
@import url(//fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700&subset=latin,latin-ext)
```

**Comment by bolandrm** [comment]
I can no longer reproduce this.  Can you try the latest version of sassc-ruby and sassc-rails?

**Comment by roman-yarovoy** [comment]
@bolandrm yep, now it's working fine, thanks)
