### ISSUE TITLE
Sass return type Map unsupported

### ISSUE THREAD

**Issue by rubenswieringa** [sass/sassc-rails#50]
**tl;dr:** Can't seem to return a hash-map from within a ruby-sassc helper-method – why is this?

---

With the following initializer (/config/initializers) in a Rails project:

```ruby
require 'sprockets/sass_functions'

module Sprockets
  module SassFunctions
    def return_sass_hash
      values = {}
      Sass::Script::Value::Map.new values
    end
  end
end

::SassC::Script::Functions.send :include, Sprockets::SassFunctions
```

And calling this method from my stylesheet:

```sass
$returned-hash: return-sass-hash();
```

I get the following error:
```
 SassC::SyntaxError: Error: error in C function return-sass-hash: Sass return type Map unsupported
 
        Backtrace:
         app/assets/stylesheets/sass_ext_test.scss:2, in function `return-sass-hash`
         app/assets/stylesheets/sass_ext_test.scss:2
         on line 2 of app/assets/stylesheets/sass_ext_test.scss
 >> $returned-hash: return-sass-hash();
    ----------------^
 
   (in /Users/ruben.swieringa/Development/caren-redesign/app/assets/stylesheets/sass_ext_test.scss)
```

---

Are maps really unsupported from within SassC-extensions? And if so, is there a timeline for supporting them?

**Comment by bolandrm** [comment]
Hello,

The LibSass bindings gem, SassC-Ruby (https://github.com/sass/sassc-ruby), does not yet support map types in custom functions.  As I only work on this in my spare time, I can't say when this might be implemented.

If you'd like to implement it yourself, I will gladly accept a pull request.  You'll have to handle the value conversions for the map type here (and add corresponding tests):
https://github.com/sass/sassc-ruby/blob/master/lib/sassc/script/value_conversion.rb

**Comment by rubenswieringa** [comment]
That doesn't sound too complicated and I'd love to have a go at it. Unfortunately I [can't seem to get tests to pass](https://github.com/sass/sassc-ruby/issues/26) – if you can give any pointers as to what might be the cause then that would be much appreciated.

**Comment by rubenswieringa** [comment]
Figured I'd go a little easy on myself and started with implementing numbers: sass/sassc-ruby#29

Assuming that you will get a notification when I make a PR for maps, then this issue can be closed as far as I'm concerned.

**Comment by bolandrm** [comment]
Great!  Thanks!  I'll go ahead and close this.  I'll review your PR when I get a moment.
