### ISSUE TITLE
Not working with Rails 4.2.5 (sassc-rails v1.1.0)

### ISSUE THREAD

**Issue by Xenofex** [sass/sassc-rails#56]
Hi all,

I realized that I have to add this hack to make sassc-rails working
```ruby
    # in application.rb
    config.after_initialize do
      Rails.application.assets.register_engine '.sass', SassC::Rails::SassTemplate
      Rails.application.assets.register_engine '.scss', SassC::Rails::ScssTemplate
    end
```

I found this by noticing that `inline_source_maps` was not working. After hours of debugging I found that sassc-rails was not registered as the handler to sass in my project. As far as I discovered, in `lib/sassc/rails/railtie.rb`, the initializer `:setup_sass` fails to register `sassc`, as `app.assets` always evaluates to `nil`. However Sprockets works without `sass-rails` gem, as it loads `sass` gem as the default sass handler itself. My project does't have a lot of sass files right now, thus it's hard to notice a difference in speed.

As a test case, simply create a new project with Rails 4.2.5, and change the default `sass-rails` to `sassy-rails`. Then by running 
```shell
$ rails runner 'p SasscTest::Application.assets.engines'
{".coffee"=>Sprockets::CoffeeScriptProcessor, ".jst"=>Sprockets::JstProcessor, ".eco"=>Sprockets::EcoProcessor, ".ejs"=>Sprockets::EjsProcessor, ".sass"=>Sprockets::SassProcessor, ".scss"=>Sprockets::ScssProcessor, ".erb"=>Sprockets::ERBProcessor}
```
you can tell that, `sassc` is not available among the engines.

Could you please investigate this? Thanks!

**Comment by bolandrm** [comment]
Hey, can you please try out version 1.2?

**Comment by Xenofex** [comment]
Coolio, I'll check it out. Thanks

**Comment by th0r** [comment]
@bolandrm I'm using 1.2.1 but have the same problem.

**Comment by th0r** [comment]
@Xenofex Have you fixed an issue with source maps generation?

**Comment by Xenofex** [comment]
@th0r My source maps seems to be fine, and I'm currently on 1.2.0
