### ISSUE TITLE
"rails g controller|scaffold ..." fails with "scss [not found]" error

### ISSUE THREAD

**Issue by christiannelson** [sass/sassc-rails#74]
Thanks for your work on sassc-rails! We switched over to using it as a default on all new projects.

When using rails generators, we noticed that generating views fails with a "scss [not found]" error. 

```
% rails g controller Widgets index show
Running via Spring preloader in process 65874
      create  app/controllers/widgets_controller.rb
       route  get 'widgets/show'
       route  get 'widgets/index'
      invoke  slim
      create    app/views/widgets
      create    app/views/widgets/index.html.slim
      create    app/views/widgets/show.html.slim
      invoke  rspec
      invoke  assets
      invoke    coffee
      create      app/assets/javascripts/widgets.coffee
       error    scss [not found]
```

This works using sass-rails. If sassc-rails is a drop in replacement for sass-rails, it seems to me that adding support for the generator would be a good idea.

If you agree, I can look into what it would take. LMK.

**Comment by jerome-diver** [comment]
is there a solution or someone interested there, we are now in jully 2018...

**Comment by CortexMic** [comment]
Is there a solution for this issue? As it is supposed to be a replacement for sass-rails deprecation, it would be nice to have this work.

**Comment by bolandrm** [comment]
A PR would be welcome for this issue!

**Comment by CortexMic** [comment]
I understand there was one here: https://github.com/sass/sassc-rails/pull/86

But there is no clue why it was closed without proper fix.

**Comment by CortexMic** [comment]
Is there any plan to fix this? This can be really annoying, and I suppose it is not complicated to fix?

**Comment by zenzei** [comment]
Related to this, not sure why but i still have a similar an issue when using scaffold with sassc-rails.
The relevant error message is 

`activesupport-5.2.2/lib/active_support/dependencies.rb:291:in `require': cannot load such file -- sass/css (LoadError)`

`Adding sass-rails as not required make scaffold to work.
gem 'sass-rails', require: false`

**Comment by jenskutilek** [comment]
> Adding sass-rails as not required make scaffold to work.
> `gem 'sass-rails', require: false`

It works, but then you get a plain CSS template file, not SCSS.

**Comment by zenzei** [comment]
> > Adding sass-rails as not required make scaffold to work.
> > `gem 'sass-rails', require: false`
> 
> It works, but then you get a plain CSS template file, not SCSS.

In my environment In my case i'm getting a file with a scss extension :confused:
