### ISSUE TITLE
no implicit conversion of Sass::Importers::Filesystem into String

### ISSUE THREAD

**Issue by asecondwill** [sass/sassc-rails#79]
On updating to rails 4.2.7.1 and sassc-rails 1.3  I'm getting this error: 

```
no implicit conversion of Sass::Importers::Filesystem into String
```

On all my asset tags, Images, Stylesheets etc, eg:

 <%= image_tag("tick.svg") %>

**Comment by josemotanet** [comment]
I have also come across this when trying to overwrite `sass-rails` with `sassc-rails`.

**Comment by arxpoetica** [comment]
Me three, me three. This is happening to me.

**Comment by josemotanet** [comment]
Thanks @arxpoetica.

**Comment by asecondwill** [comment]
I've removed compass too.  not really a fix but good enough for now.  if bourbon works with sassc then that would be a way forward for future projects.

**Comment by ncri** [comment]
Not a fix at all, how to use compass together with sassc-rails?

**Comment by xzyfer** [comment]
You cannot use compass with sassc. I suggest looking at bourbon.io

**Comment by ncri** [comment]
Ah, okay. Didn't know, thx.

Am 09.03.2017 1:32 PM schrieb "Michael Mifsud" <notifications@github.com>:

> You cannot use compass with sassc. I suggest looking at bourbon.io
>

**Comment by asecondwill** [comment]
closing i guess.
